default:
  image: docker:23-cli

  services:
    - docker:23-dind

  before_script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"

  retry: 1

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  FF_NETWORK_PER_BUILD: 1
  # Disable umask 0000. See: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1736
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
  GIT_SUBMODULE_STRATEGY: recursive
