default:
  image: docker:28-cli

  services:
    - name: docker:28-dind
      command:
        - "--feature"
        - "containerd-snapshotter=true"

  before_script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"
    - docker run --privileged --rm tonistiigi/binfmt:qemu-v9.2.2 --install arm64
    - apk --update add jq

  retry: 1

variables:
  DOCKER_DRIVER: overlayfs
  DOCKER_HOST: tcp://docker:2375
  FF_NETWORK_PER_BUILD: 1
  # Disable umask 0000. See: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1736
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
  GIT_SUBMODULE_STRATEGY: recursive
